import '@/styles/globals.css'

import { Metadata } from 'next'
import { Inter as getInter } from 'next/font/google'
import { cookies } from 'next/headers'

import { TrpcProvider } from '@/lib/trpc/provider'

const inter = getInter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TrpcProvider cookies={cookies().toString()}>{children}</TrpcProvider>
      </body>
    </html>
  )
}

export default RootLayout
export { metadata }
